//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class important_link
    {
        public int id { get; set; }
        public string banner_img { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
