//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Project.WebSite.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Account> T_Account { get; set; }
        public DbSet<T_Account_Role_Mapping> T_Account_Role_Mapping { get; set; }
        public DbSet<T_Permission> T_Permission { get; set; }
        public DbSet<T_Role> T_Role { get; set; }
        public DbSet<T_Role_Permission_Mapping> T_Role_Permission_Mapping { get; set; }
        public DbSet<important_link> important_link { get; set; }
        public DbSet<news_bulletin_info> news_bulletin_info { get; set; }
        public DbSet<related_file_download_info> related_file_download_info { get; set; }
        public DbSet<news_bulletin> news_bulletin { get; set; }
        public DbSet<fixed_pollution_control> fixed_pollution_control { get; set; }
        public DbSet<fixed_pollution_control_in> fixed_pollution_control_in { get; set; }
        public DbSet<fixed_pollution_control_info> fixed_pollution_control_info { get; set; }
        public DbSet<related_file_download> related_file_download { get; set; }
        public DbSet<system_link> system_link { get; set; }
    }
}
