//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPA.Project.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class related_file_download_info
    {
        public int id { get; set; }
        public int related_file_download_id { get; set; }
        public string sub_file { get; set; }
        public string sub_title { get; set; }
        public int sub_no { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
